module.exports = {
  autocarrot:         require("./autocarrot/_autocarrot.js"),
  autoResponses:      require("./auto_responses/_auto_responses.js"),
  coopchannels:       require("./coopchannels/_coopchannels.js"),
  economy:            require("./economy/_economy.js"),
  hangman:            require("./hangman/_hangman.js"),
  help:               require("./help/_help.js"),
  propaganda:         require("./propaganda/_propaganda.js"),
  main:               require("./_main.json"),
  admins:             require("./admins.json"),
  badges:             require("./badges.json"),
  birthdays:          require("./birthdays.json"),
  karma:              require("./karma.json"),
  logger:             require("./logger.json"),
  messageResponder:   require("./message_responder.json"),
  minesweeper:        require("./minesweeper.json"),
  mute:               require("./mute.json"),
  polls:              require("./polls.json"),
  smashOrPass:        require("./smash_or_pass.json"),
}