module.exports.main = require("./_main.json")
module.exports.admins = require("./admins.json")
module.exports.autocarrot = require("./autocarrot/_autocarrot.js")
module.exports.autoResponses = require("./auto_responses.json")
module.exports.hangman = require("./hangman/_hangman.js")
module.exports.billzo = require("./billzo/_billzo.js")
module.exports.help = require("./help/_help.js")
module.exports.coopchannels = require("./coopchannels/_coopchannels.js")