module.exports.settings = require("./_settings.json")
module.exports.interview = require("./interview.json")
module.exports.literacy = require("./literacy.json")
module.exports.messages = require("./messages.json")
module.exports.news = require("./news.json")
module.exports.placeholders = require("./placeholders.json")